package com.zzh.protos;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

public final class Protobuf {
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pb_team_infoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_team_info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string team_id = 1;</code>
     * @return The teamId.
     */
    java.lang.String getTeamId();
    /**
     * <code>string team_id = 1;</code>
     * @return The bytes for teamId.
     */
    com.google.protobuf.ByteString
        getTeamIdBytes();

    /**
     * <code>string leader_id = 2;</code>
     * @return The leaderId.
     */
    java.lang.String getLeaderId();
    /**
     * <code>string leader_id = 2;</code>
     * @return The bytes for leaderId.
     */
    com.google.protobuf.ByteString
        getLeaderIdBytes();

    /**
     * <code>repeated string members = 3;</code>
     * @return A list containing the members.
     */
    java.util.List<java.lang.String>
        getMembersList();
    /**
     * <code>repeated string members = 3;</code>
     * @return The count of members.
     */
    int getMembersCount();
    /**
     * <code>repeated string members = 3;</code>
     * @param index The index of the element to return.
     * @return The members at the given index.
     */
    java.lang.String getMembers(int index);
    /**
     * <code>repeated string members = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the members at the given index.
     */
    com.google.protobuf.ByteString
        getMembersBytes(int index);

    /**
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code pb_team_info}
   */
  public static final class pb_team_info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb_team_info)
      pb_team_infoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use pb_team_info.newBuilder() to construct.
    private pb_team_info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pb_team_info() {
      teamId_ = "";
      leaderId_ = "";
      members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new pb_team_info();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pb_team_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              teamId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                members_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              members_.add(s);
              break;
            }
            case 32: {

              status_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          members_ = members_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.internal_static_pb_team_info_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.internal_static_pb_team_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.pb_team_info.class, Protobuf.pb_team_info.Builder.class);
    }

    public static final int TEAM_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object teamId_;
    /**
     * <code>string team_id = 1;</code>
     * @return The teamId.
     */
    @java.lang.Override
    public java.lang.String getTeamId() {
      java.lang.Object ref = teamId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teamId_ = s;
        return s;
      }
    }
    /**
     * <code>string team_id = 1;</code>
     * @return The bytes for teamId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTeamIdBytes() {
      java.lang.Object ref = teamId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object leaderId_;
    /**
     * <code>string leader_id = 2;</code>
     * @return The leaderId.
     */
    @java.lang.Override
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderId_ = s;
        return s;
      }
    }
    /**
     * <code>string leader_id = 2;</code>
     * @return The bytes for leaderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList members_;
    /**
     * <code>repeated string members = 3;</code>
     * @return A list containing the members.
     */
    public com.google.protobuf.ProtocolStringList
        getMembersList() {
      return members_;
    }
    /**
     * <code>repeated string members = 3;</code>
     * @return The count of members.
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated string members = 3;</code>
     * @param index The index of the element to return.
     * @return The members at the given index.
     */
    public java.lang.String getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated string members = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the members at the given index.
     */
    public com.google.protobuf.ByteString
        getMembersBytes(int index) {
      return members_.getByteString(index);
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(teamId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, teamId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderId_);
      }
      for (int i = 0; i < members_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, members_.getRaw(i));
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(teamId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, teamId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < members_.size(); i++) {
          dataSize += computeStringSizeNoTag(members_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMembersList().size();
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protobuf.pb_team_info)) {
        return super.equals(obj);
      }
      Protobuf.pb_team_info other = (Protobuf.pb_team_info) obj;

      if (!getTeamId()
          .equals(other.getTeamId())) return false;
      if (!getLeaderId()
          .equals(other.getLeaderId())) return false;
      if (!getMembersList()
          .equals(other.getMembersList())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEAM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTeamId().hashCode();
      hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderId().hashCode();
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protobuf.pb_team_info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.pb_team_info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.pb_team_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.pb_team_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.pb_team_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.pb_team_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.pb_team_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protobuf.pb_team_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protobuf.pb_team_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protobuf.pb_team_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protobuf.pb_team_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protobuf.pb_team_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protobuf.pb_team_info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb_team_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_team_info)
        Protobuf.pb_team_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuf.internal_static_pb_team_info_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuf.internal_static_pb_team_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuf.pb_team_info.class, Protobuf.pb_team_info.Builder.class);
      }

      // Construct using Protobuf.pb_team_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        teamId_ = "";

        leaderId_ = "";

        members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuf.internal_static_pb_team_info_descriptor;
      }

      @java.lang.Override
      public Protobuf.pb_team_info getDefaultInstanceForType() {
        return Protobuf.pb_team_info.getDefaultInstance();
      }

      @java.lang.Override
      public Protobuf.pb_team_info build() {
        Protobuf.pb_team_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Protobuf.pb_team_info buildPartial() {
        Protobuf.pb_team_info result = new Protobuf.pb_team_info(this);
        int from_bitField0_ = bitField0_;
        result.teamId_ = teamId_;
        result.leaderId_ = leaderId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          members_ = members_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.members_ = members_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuf.pb_team_info) {
          return mergeFrom((Protobuf.pb_team_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuf.pb_team_info other) {
        if (other == Protobuf.pb_team_info.getDefaultInstance()) return this;
        if (!other.getTeamId().isEmpty()) {
          teamId_ = other.teamId_;
          onChanged();
        }
        if (!other.getLeaderId().isEmpty()) {
          leaderId_ = other.leaderId_;
          onChanged();
        }
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuf.pb_team_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuf.pb_team_info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object teamId_ = "";
      /**
       * <code>string team_id = 1;</code>
       * @return The teamId.
       */
      public java.lang.String getTeamId() {
        java.lang.Object ref = teamId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          teamId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string team_id = 1;</code>
       * @return The bytes for teamId.
       */
      public com.google.protobuf.ByteString
          getTeamIdBytes() {
        java.lang.Object ref = teamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string team_id = 1;</code>
       * @param value The teamId to set.
       * @return This builder for chaining.
       */
      public Builder setTeamId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        teamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string team_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeamId() {

        teamId_ = getDefaultInstance().getTeamId();
        onChanged();
        return this;
      }
      /**
       * <code>string team_id = 1;</code>
       * @param value The bytes for teamId to set.
       * @return This builder for chaining.
       */
      public Builder setTeamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        teamId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object leaderId_ = "";
      /**
       * <code>string leader_id = 2;</code>
       * @return The leaderId.
       */
      public java.lang.String getLeaderId() {
        java.lang.Object ref = leaderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leader_id = 2;</code>
       * @return The bytes for leaderId.
       */
      public com.google.protobuf.ByteString
          getLeaderIdBytes() {
        java.lang.Object ref = leaderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leader_id = 2;</code>
       * @param value The leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leader_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderId() {

        leaderId_ = getDefaultInstance().getLeaderId();
        onChanged();
        return this;
      }
      /**
       * <code>string leader_id = 2;</code>
       * @param value The bytes for leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        leaderId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          members_ = new com.google.protobuf.LazyStringArrayList(members_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string members = 3;</code>
       * @return A list containing the members.
       */
      public com.google.protobuf.ProtocolStringList
          getMembersList() {
        return members_.getUnmodifiableView();
      }
      /**
       * <code>repeated string members = 3;</code>
       * @return The count of members.
       */
      public int getMembersCount() {
        return members_.size();
      }
      /**
       * <code>repeated string members = 3;</code>
       * @param index The index of the element to return.
       * @return The members at the given index.
       */
      public java.lang.String getMembers(int index) {
        return members_.get(index);
      }
      /**
       * <code>repeated string members = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the members at the given index.
       */
      public com.google.protobuf.ByteString
          getMembersBytes(int index) {
        return members_.getByteString(index);
      }
      /**
       * <code>repeated string members = 3;</code>
       * @param index The index to set the value at.
       * @param value The members to set.
       * @return This builder for chaining.
       */
      public Builder setMembers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       * @param value The members to add.
       * @return This builder for chaining.
       */
      public Builder addMembers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       * @param values The members to add.
       * @return This builder for chaining.
       */
      public Builder addAllMembers(
          java.lang.Iterable<java.lang.String> values) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMembers() {
        members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       * @param value The bytes of the members to add.
       * @return This builder for chaining.
       */
      public Builder addMembersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {

        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb_team_info)
    }

    // @@protoc_insertion_point(class_scope:pb_team_info)
    private static final Protobuf.pb_team_info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protobuf.pb_team_info();
    }

    public static Protobuf.pb_team_info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<pb_team_info>
        PARSER = new com.google.protobuf.AbstractParser<pb_team_info>() {
      @java.lang.Override
      public pb_team_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pb_team_info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pb_team_info> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<pb_team_info> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Protobuf.pb_team_info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_team_info_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_team_info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protobuf.proto\"S\n\014pb_team_info\022\017\n\007team" +
      "_id\030\001 \001(\t\022\021\n\tleader_id\030\002 \001(\t\022\017\n\007members\030" +
      "\003 \003(\t\022\016\n\006status\030\004 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_team_info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_team_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_team_info_descriptor,
        new java.lang.String[] { "TeamId", "LeaderId", "Members", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
