mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zzh.springboot3
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 使用标准输出日志

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  shardingsphere:
    datasource:
      names: write_db0,write_db1,read1_db0,read1_db1,read2_db0,read2_db1
      write_db0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      write_db1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      read1_db0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      read1_db1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      read2_db0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      read2_db1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    rules:
      sharding:
        # 配置分片规则
        tables:
          # 配置 t_order 表规则
          t_order:
            actualDataNodes: read_write_db${0..1}.t_order_${0..1}
            # 配置分库策略
            databaseStrategy:
              standard:
                shardingColumn: id
                shardingAlgorithmName: order_database_inline
            # 配置分表策略
            tableStrategy:
              standard:
                shardingColumn: id
                shardingAlgorithmName: order_table_inline
            keyGenerateStrategy:
              column: id
              key-generator-name: snowflake
          t_user:
            actualDataNodes: read_write_db${0..1}.t_user_${0..1}
            # 配置分库策略
            databaseStrategy:
              complex:
                sharding-columns: id,role_id
                shardingAlgorithmName: user_database_complex
            # 配置分表策略
            tableStrategy:
              complex:
                sharding-columns: id,role_id
                shardingAlgorithmName: user_table_complex
            keyGenerateStrategy:
              column: id
              key-generator-name: snowflake
          t_role:
            actualDataNodes: read_write_db${0..1}.t_role_${0..1}
            # 配置分库策略
            databaseStrategy:
              complex:
                sharding-columns: id,name
                shardingAlgorithmName: role_database_complex
            # 配置分表策略
            tableStrategy:
              complex:
                sharding-columns: id,name
                shardingAlgorithmName: role_table_complex
            keyGenerateStrategy:
              column: id
              key-generator-name: snowflake
        # 配置分片算法
        sharding-algorithms:
          order_database_inline:
            type: INLINE
            props:
              algorithm-expression: read_write_db${id % 2}
          order_table_inline:
            type: INLINE
            props:
              algorithm-expression: t_order_${id % 2}
          user_database_complex:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: read_write_db${((id % 2)+(role_id%2))%2}
          user_table_complex:
            type: CLASS_BASED
            props:
              strategy: COMPLEX
              algorithmClassName: com.zzh.springboot3.shardingsphere.UserShardingAlgorithm
          role_database_complex:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: read_write_db${id % 2}
          role_table_complex:
            type: CLASS_BASED
            props:
              strategy: COMPLEX
              algorithmClassName: com.zzh.springboot3.shardingsphere.RoleShardingAlgorithm
          default_database_inline:
            type: INLINE
            props:
              algorithm-expression: read_write_db0
        #          default_table_inline:
        #            type: INLINE
        #            props:
        #              algorithm-expression: t_order_${id % 2}
        default-database-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: default_database_inline
        #        default-table-strategy:
        #          standard:
        #            sharding-column: id
        #            sharding-algorithm-name: default_table_inline
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 0  # 可配置为你希望的 worker-id
        default-sharding-column: id
      readwrite-splitting:
        data-sources:
          read_write_db0:
            static-strategy:
              read-data-source-names: read1_db0,read2_db0
              write-data-source-name: write_db0
            load-balancer-name: round_robin
          read_write_db1:
            static-strategy:
              read-data-source-names: read1_db1,read2_db1
              write-data-source-name: write_db1
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
  datasource:
    hikari:
      data-source-class-name:
logging:
  level:
    root: INFO
    org.springframework.transaction.interceptor.TransactionInterceptor: DEBUG
    org.springframework.transaction.support.TransactionSynchronizationManager: DEBUG
    org.springframework.orm.mybatis: DEBUG  # 额外增加 MyBatis 相关日志
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerA:
        slidingWindowType: COUNT_BASED    # 滑动窗口类型，支持时间或计数
        slidingWindowSize: 5       # 滑动窗口大小
        minimumNumberOfCalls: 3     # 最小调用次数，超过该值才开始判断是否要熔断
        failureRateThreshold: 50    # 失败率阈值，超过该值则开启熔断器（以百分比计算）
        waitDurationInOpenState: 60s # 熔断器打开后的等待时间，时间到后熔断器进入半开状态
        permittedNumberOfCallsInHalfOpenState: 3  # 半开状态下允许的调用次数
        automaticTransitionFromOpenToHalfOpenEnabled: true  # 自动从打开状态转换到半开状态
        maxWaitDurationInHalfOpenState: 2m   # 半开状态最多保持的时间
        #        recordExceptions:
        #          - java.io.IOException       # 记录为失败的异常类型
        #          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - com.zzh.springboot3.exception.BusinessException  # 被忽略的异常类型（这些异常不会触发熔断器）
zzh:
  resilience4j:
    circuit-breaker:
      circuitBreakerB:
        slidingWindowType: COUNT_BASED    # 滑动窗口类型，支持时间或计数
        slidingWindowSize: 5       # 滑动窗口大小
        minimumNumberOfCalls: 3     # 最小调用次数，超过该值才开始判断是否要熔断
        failureRateThreshold: 50    # 失败率阈值，超过该值则开启熔断器（以百分比计算）
        waitDurationInOpenState: 60s # 熔断器打开后的等待时间，时间到后熔断器进入半开状态
        permittedNumberOfCallsInHalfOpenState: 3  # 半开状态下允许的调用次数
        automaticTransitionFromOpenToHalfOpenEnabled: true  # 自动从打开状态转换到半开状态
        maxWaitDurationInHalfOpenState: 2m   # 半开状态最多保持的时间
